apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: '.'
    repoURL: 'https://github.com/AmineBarboura/abarbour.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
