Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.boot_timeout = 600
        config.vm.define "adjemaaS" do |master|
	  master.vm.network "private_network", ip: "192.168.56.110"
	  master.vm.hostname = "adjemaaS"
	  master.vm.provider "virtualbox" do |vb|
		  vb.memory = "1024"
		  vb.cpus = "1"
		  vb.name = "adjemaaS"
	  end
          master.vm.provision "shell", path: "./scripts/script.sh"
      end
end